### ISSUE TITLE
Create a Node.js  / GraphQL endpoint

### ISSUE THREAD

**Issue by pA1nD** [FundacionParaguaya/stoplight-server#1]
This task aims to create backwards compatibility of the new way of survey taking. This will allow us to enable the current web app to do the reporting with the existing APIs while we can create the new web app progressively piece by piece.

This ensures stability of the migration process and backward compatibility with existing technology so that clients can have a smooth transition into the new stack.

Scope:
- Setup a nodejs server
- Create the /graphql endpoint to be reachable by the app (route through in Spring/Boot/Tomcat) or set it up under another domain or have a proxy server routing requests based on the URI.
- Implement the Graphql endpoint w/o breaking changes. Exactly as the Java server implements it at the moment.
- Store the data in addition in the old format so it becomes accessible via the current web app analytics.

---------

Subtasks:
- Create full documentation on how GQL API should behave
- Define user access levels. How is it at the moment?
- Send Screenshots and Database Snapshot to Domi and Discuss with him.

### Acceptance Criteria
- [x] Node Server Exists
- [ ] Continuous integratino delpoys from master
- [x] Node can connect to PG database
- [ ] Stores data in database (both in old & new schemas)
- [ ] Errors are posted in Slack within 5 minutes
- [ ] Logs all requests (to prevent dataloss)
- [x] GraphQL query works
- [ ] graphQL Mutation works
- [x] GrapiQL works
- [ ] Authenticates properly - No data leaks + correct information given to users
